name: Application Pipeline

on:
  push:
    branches:
      - master
    paths:
      - "app/**"

defaults:
  run:
    working-directory: ./app

jobs:
  build:
    uses: ./.github/workflows/reusable/app-build.yml

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: demo-api
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/demo-api.tar

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
        with:
          mask-password: true

      - name: Publish Docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: demo-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag demo-api:latest "$REGISTRY/$REPOSITORY:$IMAGE_TAG"
          docker push "$REGISTRY/$REPOSITORY:$IMAGE_TAG"
          docker push "$REGISTRY/$REPOSITORY:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      
      # TODO check for creds + roles
      - name: Redeploy ECS service
        env:
          ECS_CLUSTER: ecs-cluster
          ECS_SERVICE: demo-api
        run: |
          aws ecs update-service \
            --cluster "$ECS_CLUSTER" \
            --service "$ECS_SERVICE" \
            --force-new-deployment
