name: Application Pipeline

on:
  push:
    branches:
      - master
    paths:
      - "app/**"

defaults:
  run:
    working-directory: ./app

jobs:
  build:
    uses: ./.github/workflows/reusable/app-build.yml@main

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      
      # TODO check for creds + roles
      - name: Redeploy ECS service
        env:
          ECS_CLUSTER: ecs-cluster
          ECS_SERVICE: demo-api
        run: |
          aws ecs update-service \
            --cluster "$ECS_CLUSTER" \
            --service "$ECS_SERVICE" \
            --force-new-deployment
