name: Infrastructure Pipeline

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      INFRA_DIR: "infra"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install tools
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Validate
        run: |
          terraform -chdir="$INFRA_DIR" init -backend=false
          terraform -chdir="$INFRA_DIR" validate

      - name: Check fmt
        run: terraform fmt -recursive -check "$INFRA_DIR"

      - name: Check tflint
        run: |
          CURRENT_DIR="$(pwd)"
          cd "$INFRA_DIR"
          tflint --recursive
          cd "$CURRENT_DIR"

      - name: Check tfsec
        run: tfsec "$INFRA_DIR"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: eu-central-1
      INFRA_DIR: "infra"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/TerraformPipeline
          role-session-name: pipeline-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Change Terraform profile
        run: |
          sed -i 's|profile.*||g' "$INFRA_DIR/backend.tf"
          sed -i 's|profile.*||g' "$INFRA_DIR/provider.tf"

      - name: Apply
        run: |
          terraform -chdir="$INFRA_DIR" init
          terraform -chdir="$INFRA_DIR" apply -auto-approve
