name: Infrastructure PR Pipeline

on:
  pull_request:
    paths:
      - "infra/**"

jobs:
  debug:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/TerraformPipeline
          role-session-name: pipeline-session
          aws-region: eu-central-1

  plan:
    # TODO
    needs: debug
    uses: ./.github/workflows/infra-base.yml
    with:
      mode: "plan"
    permissions:
      id-token: write
      contents: read
  
  comment:
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ needs.plan.outputs.command }}"
            })

