name: Infra Pipeline

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"

jobs:
  build:
    uses: ./.github/workflows/infra-base.yml
    with:
      mode: "apply"
    permissions:
      id-token: write
      contents: read
