name: Infrastructure Pipeline

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"

defaults:
  run:
    working-directory: ./infra

jobs:
  test:
    uses: ./.github/workflows/infra-test.yml

  apply:
    runs-on: ubuntu-latest
    needs: test
    concurrency:
      group: terraform-apply
      cancel-in-progress: false
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: eu-central-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/TerraformPipeline
          role-session-name: pipeline-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.1"

      - name: Change Terraform profile
        run: |
          sed -i 's|profile.*||g' "backend.tf"
          sed -i 's|profile.*||g' "provider.tf"

      - name: Run terraform apply
        run: |
          terraform init
          terraform apply -auto-apply
