name: Infrastructure PR Pipeline

on:
  pull_request:
    paths:
      - "infra/**"

jobs:
  plan:
    uses: ./.github/workflows/infra-base.yml
    with:
      mode: "plan"
    permissions:
      id-token: write
      contents: read
