name: Infrastructure Base Pipeline

on:
  workflow_call:

defaults:
  run:
    working-directory: ./infra

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install tools
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Validate
        run: |
          terraform init -backend=false
          terraform validate

      - name: Check fmt
        run: terraform fmt -recursive -check .

      - name: Check tflint
        run: tflint --recursive

      - name: Check tfsec
        run: tfsec

