name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install tools
        run: |
          pip install black isort mypy ruff

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint code
        run: |
          black --check app
          isort --profile black app
          mypy app
          ruff check app

  # https://docs.docker.com/build/ci/github-actions/share-image-jobs/
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: demo-api:latest
          outputs: type=docker,dest=/tmp/demo-api.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: demo-api
          path: /tmp/demo-api.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest tests

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: demo-api
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/demo-api.tar

      - name: Tag image
        run: docker tag demo-api:latest public.ecr.aws/d2v5d2j3/demo-api:${{ github.sha }}

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish Docker image to ECR
        run: |
          docker push public.ecr.aws/d2v5d2j3/demo-api:${{ github.sha }}
